void info() {
  background(backgroundColour);
  noStroke();
  fill(buttonColour);
  rect(400, 250, 700, 400, 10);
  
  //text
  fill(textColour);
  titleFont = createFont("The Wild Breath of Zelda.otf", 75);
  textFont(titleFont);
  text("Hyrule is under attack!!", 400, 100);
  textSize(18);
  text("THE DIVINE BEASTS HAVE ONCE AGAIN BEEN ATTACKED BY CALAMITY GANON! NOW, IT IS UP \n TO YOU TO DEFEAT THE BOSSES INSIDE... IN SPACE!", 400, 180); 
  text("CONTROLS: USE THE ARROW KEYS TO MOVE YOUR PLAYER AND SPACE TO SHOOT THE ENEMIES. \n TO DENOTE A BOMB, PRESS 'A'. YOUR GOAL IS TO DEFEAT THE MAIN BOSS. \n KILLING CERTAIN ENEMIES CAN PROVIDE YOU WITH POWERUPS TO IMPROVE YOUR SKILLS.", 400, 255);
  text("FOR EACH ENEMY YOU KILL, YOU WILL BE AWARDED POINTS THAT WILL LATER ALLOW YOU \n TO UNLOCK NEW CHAMPIONS TO BOOST YOUR SCORE. UNFORTUNATELY, FOR EACH ENEMY \n YOU DON'T KILL, POINTS WILL BE DEDUCTED FROM YOUR FINAL SCORE.", 400, 350);
  textSize(30);
  text("GOOD LUCK, AND GO SAVE HYRULE!!", 400, 415);
}

void infoClicks() {
  mode = INTRO;
}
